

countries_wikidata = {
    "afghanistan": "Q889", "albania": "Q222", "algeria": "Q262", "andorra": "Q228", "angola": "Q916",
    "antigua and barbuda": "Q781", "argentina": "Q414", "armenia": "Q399", "australia": "Q408",
    "austria": "Q40", "azerbaijan": "Q227", "bahamas": "Q778", "bahrain": "Q398", "bangladesh": "Q902",
    "barbados": "Q244", "belarus": "Q184", "belgium": "Q31", "belize": "Q242", "benin": "Q962",
    "bhutan": "Q917", "bolivia": "Q750", "bosnia and herzegovina": "Q225", "botswana": "Q963",
    "brazil": "Q155", "brunei": "Q921", "bulgaria": "Q219", "burkina faso": "Q965", "burundi": "Q967",
    "cabo verde": "Q1011", "cambodia": "Q424", "cameroon": "Q1009", "canada": "Q16",
    "central african republic": "Q929", "chad": "Q657", "chile": "Q298", "china": "Q148",
    "colombia": "Q739", "comoros": "Q970", "congo, democratic republic of the": "Q974",
    "congo, republic of the": "Q971", "costa rica": "Q800", "côte d'ivoire": "Q1008",
    "croatia": "Q224", "cuba": "Q241", "cyprus": "Q229", "czech republic": "Q213", "denmark": "Q35",
    "djibouti": "Q977", "dominica": "Q784", "dominican republic": "Q786", "ecuador": "Q736",
    "egypt": "Q79", "el salvador": "Q792", "equatorial guinea": "Q983", "eritrea": "Q986",
    "estonia": "Q191", "eswatini": "Q1050", "ethiopia": "Q115", "fiji": "Q712", "finland": "Q33",
    "france": "Q142", "gabon": "Q1000", "gambia": "Q1005", "georgia": "Q230", "germany": "Q183",
    "ghana": "Q117", "greece": "Q41", "grenada": "Q769", "guatemala": "Q774", "guinea": "Q1006",
    "guinea-bissau": "Q1007", "guyana": "Q734", "haiti": "Q790", "honduras": "Q783", "hungary": "Q28",
    "iceland": "Q189", "india": "Q668", "indonesia": "Q252", "iran": "Q794", "iraq": "Q796",
    "ireland": "Q27", "israel": "Q801", "italy": "Q38", "jamaica": "Q766", "japan": "Q17",
    "jordan": "Q810", "kazakhstan": "Q232", "kenya": "Q114", "kiribati": "Q710", "korea, north": "Q423",
    "korea, south": "Q884", "kuwait": "Q817", "kyrgyzstan": "Q813", "laos": "Q819", "latvia": "Q211",
    "lebanon": "Q822", "lesotho": "Q1013", "liberia": "Q1014", "libya": "Q1016", "liechtenstein": "Q347",
    "lithuania": "Q37", "luxembourg": "Q32", "madagascar": "Q1019", "malawi": "Q1020", "malaysia": "Q833",
    "maldives": "Q826", "mali": "Q912", "malta": "Q233", "marshall islands": "Q709", "mauritania": "Q1025",
    "mauritius": "Q1027", "mexico": "Q96", "micronesia": "Q702", "moldova": "Q217", "monaco": "Q235",
    "mongolia": "Q711", "montenegro": "Q236", "morocco": "Q1028", "mozambique": "Q1029", "myanmar": "Q836",
    "namibia": "Q1030", "nauru": "Q697", "nepal": "Q837", "netherlands": "Q55", "new zealand": "Q664",
    "nicaragua": "Q811", "niger": "Q1032", "nigeria": "Q1033", "north macedonia": "Q221", "norway": "Q20",
    "oman": "Q842", "pakistan": "Q843", "palau": "Q695", "panama": "Q804", "papua new guinea": "Q691",
    "paraguay": "Q733", "peru": "Q419", "philippines": "Q928", "poland": "Q36", "portugal": "Q45",
    "qatar": "Q846", "romania": "Q218", "russia": "Q159", "rwanda": "Q1037", "saint kitts and nevis": "Q763",
    "saint lucia": "Q760", "saint vincent and the grenadines": "Q757", "samoa": "Q683",
    "san marino": "Q238", "sao tome and principe": "Q1039", "saudi arabia": "Q851", "senegal": "Q1041",
    "serbia": "Q403", "seychelles": "Q1042", "sierra leone": "Q1044", "singapore": "Q334",
    "slovakia": "Q214", "slovenia": "Q215", "solomon islands": "Q685", "somalia": "Q1045",
    "south africa": "Q258", "south sudan": "Q958", "spain": "Q29", "sri lanka": "Q854",
    "sudan": "Q1049", "suriname": "Q730", "sweden": "Q34", "switzerland": "Q39", "syria": "Q858",
    "taiwan": "Q865", "tajikistan": "Q863", "tanzania": "Q924", "thailand": "Q869", "timor-leste": "Q574",
    "togo": "Q945", "tonga": "Q678", "trinidad and tobago": "Q754", "tunisia": "Q948", "turkey": "Q43",
    "turkmenistan": "Q874", "tuvalu": "Q672", "uganda": "Q1036", "ukraine": "Q212",
    "united arab emirates": "Q878", "united kingdom": "Q145", "united states": "Q30", "uruguay": "Q77",
    "uzbekistan": "Q265", "vanuatu": "Q686", "vatican city": "Q237", "venezuela": "Q717", "vietnam": "Q881",
    "yemen": "Q805", "zambia": "Q953", "zimbabwe": "Q954"
}


stopwords = ['school', 'negeri', 'of', 'sd', 'primary', 'and', 'hotel', 'de', 'university', 'smp',
            'library', 'the', 'high', '1', 'college', 'biblioteca', '2', 'gbps', '&', '-', 'institute',
            'municipal', 'for', 'public', 'di', 'oyo', 'department', 'hospital', '3', 'smk', 'in', 
            'sma', 'elementary', 'academy', 'district', 'city', 'international', 'centre', 'nursery', 
            'house', 'la', 'state', 'mts', 'ssk', 'national', 'club', 'center', 'society', 'inn', '(united',
            'health', 'college,', 'pública', 'community', '4', 'del', 'council', 'embassy', 'group', 'sub-centre',
            'foundation', 'association', 'scuola', 'mas', 'research', 'technology', 'states)', 'school,',
            'company','al', 'new', 'science', 'catholic', 'p', 'medical', 'f.c.', 'sciences', 'resort', 'i',
            'secondary', 'education','st', 'inpres', '5', 'county', 'fc', 'st.', 'faculty', 'p.', 'park',
            'san', 'central', 'f', 'comunale', 'hostel','engineering', 'ggps', 'e', 'government', 'muhammad'
            , 'records', 'corporation', 'trust', 'junior', 'branch', 'ministry', 'f.', 'arts', 'islam', 
            'south', 's', 'bank', 'north', 'ii', 'on', 'memorial', 'middle', '6', 'a', 'west', 'management',
              'united', 's.', 'church', 'royal', 'roman', 'und', 'für', 'by', 'limited', 'khan', 'studies'
            , 'centro', 'jr.', 'police', 'development', 'general', 'da', 'guest', 'lodge', 'east', 'court',
            'basic', '7', 'institut', 'it', 'des', 'spa', 'muhammadiyah', 'o', 'villa', 'beach', 'saint',
            'schools', 'office', 'do', 'at', 'diocese', 'music', 'el', 'via', 'girls', 'american', 'historical',
            'grand', 'business', 'service', 'inc.', 'capital', 'england', '8', 'services', 'air', 'suites', 
            'degree', 'senior', 'valley', 'social', 'commission', 'y', 'regional', 'union', 'town', 'media', 
            'primaria', 'art', 'first', 'technical', 'plus', 'law', 'boutique', 'et', 'satu', 'santa', 
            'della', 'du', 'selatan', 'nurul', 'garden', 'atap', 'home', 'medicine', '9', 'cabinet', 
            'football', 'bookstore', 'railway', 'ali', 'energy', 'mahavidyalaya,', 'station', "women's", 
            'škola', 'maria', 'board', 'casa', 'rural', 'barat', 'escola', 'co.', 'collection', 'palace', 
            'sungai', 'le', 'hill', 'utara', 'universidad', 'g.', 'productions', 'a.', 's.s.k', 'spot', 
            'information', 'western', '10', 'sri', 'systems', 'kingdom)', 'jaya', 'tinggi', 'private', "men's", 
            'ltd.', 'christian', 'green', 'model', 'islamiyya', 'slb', 'care', 'technologies', 'tengah', 
            'sekolah', 'gmbh', 'global', 'darul', 'timur', 'agency', 'kota', 'nursing', 'islamic', '11', 
            'ecole', 'entertainment', 'old', 'pgri', 'studio', 'tanjung', 'en', 'liceo', 'van', 'film', 'federal', 
            'london', 'flagship', 'para', 'haji', 'authority', 'independent', 'republic', 'der', 'reddoorz', 
            'infanzia', 'instituto', 'min', '@', 'design', 'lake', 'sc', 'education,', 'arms', 'commerce', 'area', 
            'faculdade', 'vocational', "dell'infanzia", 'john', 'bux', 'materna', 'holdings', 'life', 'european', 
            'studi', 'bay', 'lps', '12', 'popular', 'red', 'museum', 'films', 'japan', 'universität', 'jakarta', 
            'ltd', 'b', 'network', 'ss', 'to', 'l.', 'world', 'f.p.', 'training', 'village', 'iii', 'hall', 
            'residency', 'basketball', 'm.', 'indonesia', "girls'", 'campus', 'theatre', 'family', 'residence', 
            'golf', 'restaurant', 'cofe', 'plaza', 'york', 'don', 'china', 'degli', 'street', 'economics', '13', 
            'gallery', 'municipality', 'history', 'apartments', 'system', 'guesthouse', 'archives', 'infant', 
            'road', 'games', 'blue', 'ulum', 'river', 'team', 'govt.', 'sv', 'hilton', 'v', 'rada', 'view', 
            'real', 'fk', 'm', 'i.c.', 'syariah', 'golden', 'satap', '(germany)', 'czech', 'studios', 'motel', 
            'free', 'children', 'baru', 'dr.', 'island', '14', 'english', 'shri', 'higher', 'special', 'tokyo', 
            'd/a', 'mis', 'california', 'applied', 'federation', 'learning', 'università', 'sports', 'holding', 
            'finance', 'british', 'division', 'holiday', 'star', 'silska', 'msk', 'j.', 'environmental', 
            'société', 'batu', 'southern', 'vidyalaya', 'c.', 'power', 'administration', 'open', 'homestay', 
            'gymnasium', '15', 'society,', 'youth', 'food', 'best', 'no', 'nagar', 'near', 'heritage', 
            's.s.k.', 'affairs', 'shah', 'technology,', 'computer', 'istituto', 'nw', 'shrine', 'nacional', 
            'texas', 'committee', 'muara', 'software', 'no.', 'huda', 'fund', 'agricultural', 'uttar', 'country', 
            'resources', 'airport', 'h.', 'ilmu', 'industrial', 'washington', 'základní', 'u', 'akademi', 
            'clinic', 'los', 'human', 'hotel,', 'digital', 'women', 'industries', 'mateřská', 'il', 'great', 
            '16', '17', 'e.', 'dakshin', 'data', 'prefectural', 'airlines', 'military', 'industry', 
            'polytechnic', 'nu', 'mount', 'les', 'colony', 'bar', 'civica', 'ag', 'northern', 'lgea', 'b&b', 
            'motor', 'mountain', 'hotels', "dell'istituto", 'king', 'berlin', 'gbhs', 'cz', 'express', 
            'singh', 'transport', 'medan', "children's", 'works', 'farm', 'paris', 'b.', '(norway)', 'dei', 
            'alliance', 'glps', 'cross', 'culture', 'superior', 'são', 'giovanni', 'josé', 'water', 'communauté', 
            'am', 'raya', 'way', '(canada)', 'bina', 'bureau', 'karya', 'investment', 'cultural', 'abdul', 
            'pacific', 'white', 'port', 'australian', 'fire', 'pagi', 'sk', 'nhs', 'educational', 'man', 
            'township', 'thomas', '–', 'tk', 'padang', 'école', 'hulu', 'universitas', 'bali', 'escuela', 
            'ssk.', 'states', 'mission', 'solutions', 'purba', 'an', '18', 'electric', 'kristen', 'security', 
            'florida', 'cancer', 'agriculture', 'hôtel', 'laboratory', 'methodist', 'marriott', 'civil', 
            'all', 'forest', 'grammar', 'dan', 'baseball', 'terpadu', 'local', 'victoria', 'stay', 'per', 
            'natural', 'iv', 'consulate', 'point', 'ic', 'clube', 'r.', 'eastern', 'brewery', 'trade', 'na', 
            'sport', 'nusantara', 'bengkulu', 'jr', 'seoul', 'pousada', 'villas', 'african', 'communications', 
            'serale', 'l', 'rio', 'advanced', 'metropolitan', '19', 'railroad', 'estate', 'co.,', 'fond', 'gblss', 
            'black', 'gunung', 'economic', 'land', 'post', 'co', 'holy', "mary's", 'pulau', 'george', 'australia', 
            'aviation', 'las', 'h', 'mandiri', 'africa', 'clinical', '21', 'marine', 'statale', 'riad', 'hills', 
            'canada', 'project', 'ghulam', 'bus', 'india', 'vidyapith', '20', 'communication', 'pharmacy', 'urban', 
            'insurance', '(czechia)', 'graduate', 'k', 'america', 'carolina', 'seminary', 'scientific', 'harapan', 
            "qur'an", 
            'little', 'castle', 'tsv', 'kg', 'vidya', 'balika', "ma'arif", "people's", 'one', 'production', 
            'botanical', 'j', 
            'preparatory', 'palembang', 'colegio', 'organization', 'boys', 'coast', 'policy', 'repository', 'pur', 
            'lectura', 'koto', 'day', 'ups', 'german', 'communes', 'francisco', 'bed', 'child', 'indian', 'antonio', 
            'creek', 'privat', 'building', 'mahila', 'montessori', 'environment', 'second', 'gaa', 'press', 'bangsa', 
            'transit', 'as', 'facultad', 'educatiu', 'rock', 'provincial', 'paritaria', 'up', 'executive', 'v.', 
            'justice', 
            'financial', 'soccer', 'gardens', '(france)', 'c', 'korea', 'partners', 'halmahera', 'voluntary', 'plant', 
            'language', 'mary', 'd.', 'miftahul', 'islamiyya,', 'primaire', 'taipei', 'hostal', 'hilir', 'league', 
            'james', '(sweden)', 'biology', 'chemistry', 'libraries', 'professional', 'springs', 'hong', 
            'casino', 'paschim', 'g', 'georgia', 'capoluogo', 'plan', 'fort', 'psychology', 'sea', 'place', 
            'modern', 'grade', 'hospital,', '(china)', 'virginia', 'kuala', 'heart', 'pictures', 'europe', 
            'humanities', 'main', 'upper', '22', 'emef', 'sun', 'breakfast', 'townhouse', 'william', 'santo', 
            'architecture', 'wyndham', 'agung', 'nursery/primary', 'associates', 'rose', 'deutsche', 'archdiocese', 
            'hs', 'scienze', 'manor', 'kong', 'alam', 'redpartner', 'unit', 'nagoya', 'baptist', 'allah', 
            'program', 'beijing', 'mathematics', 'das', 'foreign', 'charles', 'r', 'hope', 'canadian', 
            'kesehatan', 'bridge', 'rifle', 'ocean', 'delle', 'lady', 'long', 'sezione', 'chicago', '24', 
            'heights', 'maluku', 'gesellschaft', 'paul', 'moscow', 'onsen', 'bhakti', 'universidade', 
            'krishna', 'maine', 'chemical', 'university,', 'grande', 'cap.', 'architects', 'bandar', 'tree', 
            'ahmed', 'bumi', 'academic', 'construction', 'television', 'organizace', 'cafe', 'light', 
            'devi', '23', 'khoso', 'invest','dazione', 'a.s.', 'vehicles', 'dental', 'illinois', 'giusedazione', 
            'a.s.', 'vehicles', 'dental', 'illinois', 'giuseppe', 'tanah', 'grove', 'library,', 'příspěvková', 
            'if', 'mercure', 'crown', 'rights', 'pharmaceutical', 'colorado', 'japanese', 'fine', 'our', 
            'bosco', 'aided', 'mining', 'korean', 'trinity', 'muslim', 'massachusetts', 'putra', 'malam', 
            'shanghai', 'taman', 'greater', 'commercial', 'uganda', 'sari', 'café', 't.', 'political', 
            'trading', 'army', 'makmur', 'shree', 'stiftelsen', 'falah', 'safety', 'ram', 'comprehensive', 
            'ab', 'tech', 'management,', 'camp', 'delta', 'ysgol', 'factory', 'square', 'ciencias', 'joseph', 
            'manufacturing', 'transportation', 'line', 'mineral', 'dipartimento', 'apartment', 'boston', 
            'asia', 'pro', 'bukit', 'steel', 'n', 'em', 'u.', 'housing', 'sai', 'ibis', 'ireland', 'chamber', 
            'gandhi', 'alps', 'jewish', 'praha', 'dos', 'w.', 'energi', 'madrid', 'münchen', '/', 'electronics', 
            'physical', 'market', 'good', '25', 'tv', 'nova', 'agencia', 'w', 's.r.o.', 'louis', 'jambi', 
            'dharma', 'museo', 'sei', 'singapore', 'grace', 'hut', 'rooms', 'mulia', 'credit', 'narrenzunft', 
            'institution', 'theological', 'action', 'chak', "joseph's", 'russian', 'anglican', 'municipales', 
            'investments', 'sc.', 'n.', 'scientifico', 'divadlo', 'airways', 'mar', 'backpackers', 'connecticut', 
            'insan', 'israel', 'spring', 'prince', 'planning', 'vista', 'tigers', 'dar', 'engineering,', 'gas', 
            'sms', 'kg/primary', 'bara', 'archive', 'utama', 'metro', 'imperial', 'prague', 'veterinary', 
            'former', 'publishing', 't']